server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flowers-marketplace
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
